[package]
name = "mini-calc-lib"
version = { workspace = true }
license = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
confy = "0.5.1"
ansi_term = "0.12.1"
